"""add embedding fields to model_configs

Revision ID: cdb3007f24e2
Revises: 8eca43b2448a
Create Date: 2026-08-06 23:54:51.063199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb3007f24e2'
down_revision: Union[str, Sequence[str], None] = '8eca43b2448a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('embedding_model', sa.String(length=128), nullable=True))
    op.add_column('model_configs', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'embedding_dimensions')
    op.drop_column('model_configs', 'embedding_model')
    # ### end Alembic commands ###
